### ISSUE TITLE
Support of dtype = float32?

### ISSUE THREAD

**Issue by lpanaf** [facebookresearch/theseus#656]
Hi, thanks for the nice library. However, while using the function, I realized that in the BaSpaCho solver, the input is forced to convert to double type. Do you plan to support float32 in the future? Or is there any reason that float32 is not used? Thank you very much in advance.

**Comment by maurimo** [comment]
BaSpaCho C++ library supports both float and double as first class citizens and tests cover both, for instance:
https://github.com/facebookresearch/baspacho/blob/main/baspacho/tests/CudaFactorTest.cpp#L231

That said, Theseus python extlib and wrappers just work with double for simplicity and also because when the systems are ill conditioned anyway floats are a very bad choice:
https://github.com/facebookresearch/theseus/blob/main/theseus/extlib/baspacho_solver_cuda.cu
In short, unless you *really* know what you're doing you're better off converting to double while solving the optimization's linear system anyway, and Theseus does it for you. You probably have very little to gain there in terms of mem-usage and speed while numerical issues might arise, so even supporting floats there I would maintain the conversion to double as being the default. Notice this is only inside the solver library, while everything else keeps working with floats as usual.

Anyway, it should not be a lot of work templating that code and making it work with float32 as well, and then we could add an (non-default) option to solve the linear system using floats. If anyone feels contributing a patch it would be nice offering this possibility as well.

**Comment by lpanaf** [comment]
Hi, thank you very much for the response. I think the ill-conditioned situation might indeed be a problem. I have tried very briefly modifying the code to support float32. It worked for CPU-based solver, but for GPU-based one, the optimization cost becomes NAN after several iterations. I was hoping you have a better implementation than mine or you have more experience on this. In this case, I would stick to the double precision.
