### ISSUE TITLE
`LUCudaSparseSolver` throws `AttributeError` in simple example

### ISSUE THREAD

**Issue by luisenp** [facebookresearch/theseus#88]
## 🐛 Bug

This [test](https://github.com/facebookresearch/theseus/blob/090cd4f1eb6aa47677091b274cf067acb2ae5948/theseus/optimizer/nonlinear/tests/test_levenberg_marquardt.py#L53) fails with 

![image](https://user-images.githubusercontent.com/4759586/154760048-f1194229-b4ea-4624-9671-95ca194115a6.png)

Looks like [this](https://github.com/facebookresearch/theseus/blob/main/theseus/optimizer/linear/lu_cuda_sparse_solver.py#L42) line should go above line 39. Curious to know how this was passing the other tests.

**Comment by maurimo** [comment]
In the test it succeeded because reset is called externally (after setting the linearization externally, instead of the normal usage where the linearization is create in the constructor).

**Comment by maurimo** [comment]
So your test (@luisenp) still fails for another reason, but the reason is that the data are on the CPU when the device should instead be CUDA. Not sure if this should be fixed in the LUCudaSparseSolver, I think the solver should do no implicit conversion, as it may make it hard to be aware of CPU<->GPU data movements occurring under the hoods, but the data given as input should indeed be in cuda tensors.

**Comment by luisenp** [comment]
I agree, I'll fix the test. Thanks!
